extends: airbnb

env:
  node: true
  es6: true

rules:
  indent: ["warn", 4]
  no-console: "off"
  spaced-comment: "off"
  prefer-const: "off"
  no-plusplus: "off"
  no-bitwise: "off"
  no-continue: "warn"
  prefer-template: "off"
  no-unused-vars: "off"
  no-trailing-spaces: "off"
  no-multiple-empty-lines: "off"
  padded-blocks: "off"
  camelcase: "off"
  prefer-destructuring: "off"
  comma-dangle: "off"
  array-bracket-spacing: ["warn", "always", { singleValue: "off" }]
  no-multi-spaces: "off"
  no-multi-str: "off"
  brace-style: ["error", "stroustrup", { "allowSingleLine": true }]
  max-len: ["warn", { "code": 120 }]

  