parser: "babel-eslint"

plugins:
  - react

extends:
  - airbnb
  - plugin:react/recommended

env:
  browser: true
  es6: true

rules:
  indent: ["warn", 4]
  react/jsx-indent: ["warn", 4]
  react/jsx-indent-props: ["warn", 4]
  react/jsx-filename-extension: "off"
  react/prefer-stateless-function: "off"
  arrow-parens: "off"
  no-console: "off"
  spaced-comment: "off"
  prefer-const: "off"
  no-plusplus: "off"
  no-bitwise: "off"
  no-continue: "warn"
  #prefer-template: "off"
  no-unused-vars: "off"
  no-trailing-spaces: "off"
  no-multiple-empty-lines: "off"
  padded-blocks: "off"
  camelcase: "off"
  prefer-destructuring: "off"
  comma-dangle: "off"
  array-bracket-spacing: ["warn", "always", { singleValue: false }]
  quotes: ["error", "single", { allowTemplateLiterals: true }]
  arrow-body-style: "off"
  no-nested-ternary: "off"
  no-multi-spaces: "off"
  no-alert: "off"
